first step for setting up 2 column
OregonDigital/OD2 pull request #1416
Opened 2020-12-10 21:20 UTC by straleyb

2020-12-14 22:40 UTC, straleyb commented
<img width="986" alt="Screen Shot 2020-12-14 at 2 38 36 PM" src="https://user-images.githubusercontent.com/6424683/102144406-4a352200-3e1a-11eb-9ac0-86a8883b8ab1.png">

2020-12-16 17:15 UTC, CGillen requested changes

2020-12-16 17:15 UTC, CGillen commented on app/views/hyrax/base/_show_collection_header.html.erb
> +  <% @member_work_2 = Hyrax::SolrService.query("member_of_collection_ids_ssim:#{@presenter.member_of_collection_ids.first}", fl: 'id', rows: 3).first['id'] %>
Should theses go back to `first`, `second`, `third`?

2020-12-16 17:15 UTC, CGillen commented on app/views/hyrax/homepage/_home_content.html.erb
> +        <% @member_work_2 = Hyrax::SolrService.query("member_of_collection_ids_ssim:#{collection.id}", fl: 'id', rows: 3).first['id'] %>
Same here? `first`, `second`, `third`?

2020-12-16 17:15 UTC, CGillen commented on app/views/hyrax/homepage/_home_content.html.erb
> +            <h4><%= Hyrax::SolrService.query("member_of_collection_ids_ssim:#{collection.id}", fl: 'id', rows: 10000).length %> items
The collection is queried multiple times. I know `Hyrax::SolrService` does some caching, but should we query once and reference the results multiple times?
```
@member_docs = Hyrax::SolrService.query("member_of_collection_ids_ssim:#{collection.id}", fl: 'id', rows: 10000)
@member_works = @member_docs[0..2].each do |doc|
  ActiveFedora::Base.find(doc['id']).members.to_a.delete_if { |work| !work.class.to_s.include?('FileSet') }.first
end
@member_count = @member_docs.length
```
Or something to that effect?

2020-12-16 20:38 UTC, CGillen approved these changes

2020-12-16 20:38 UTC, merged