[WIP] Feature/add other citations in
OregonDigital/OD2 pull request #1632
Opened 2021-04-20 21:50 UTC by straleyb

Still working on tests and making sure they render proper

2021-04-21 19:57 UTC, straleyb commented
![Uploading Screen Shot 2021-04-21 at 12.57.07 PM.png…]()

2021-04-21 19:58 UTC, straleyb commented
<img width="1591" alt="Screen Shot 2021-04-21 at 12 57 07 PM" src="https://user-images.githubusercontent.com/6424683/115613434-3ce4e400-a2a1-11eb-9f72-ab3d3d68e7e5.png">

2021-04-21 20:49 UTC, CGillen requested changes

2021-04-21 20:49 UTC, CGillen commented on app/views/hyrax/base/_citations.html.erb
>        <h3><%= t('.header') %></h3>
Lets convert all this to the same method. Either all in partial or all in translations. Translations is probably better.

2021-04-22 14:52 UTC, CGillen approved these changes

2021-04-22 14:52 UTC, merged