updates layout and missing thumbs
OregonDigital/OD2 pull request #2626
Opened 2022-12-05 21:50 UTC by straleyb

2022-12-05 21:52 UTC, straleyb commented
There are still questions that need to be answered such as:
"Are we still doing the first time here and dig deeper links" and
"Do we want the masthead image to be changing on rotation or is it fine just staying that one image (blimp image)"

2022-12-06 14:32 UTC, jsimic commented
@straleyb Yes, we still want the First time here? and Dig deeper sections. Yes, we want a rotating masthead image.

2022-12-07 17:10 UTC, CGillen requested changes

2022-12-07 17:10 UTC, CGillen commented on app/views/hyrax/homepage/_home_content.html.erb
> +        <% if @member_works.length == 0 %>
This _**should**_ create an array like how we would want.
Take our array, pad it to 3 vals (or noop if >3 length already), grab the first 3, reverse it so nils are first, then choose placeholder or thumbnail depending on nil status.

The caveat here is that `#fill` mutates the original array. So you might need to call `#dup` on `@member_works` and work with a new array

2022-12-07 17:14 UTC, straleyb commented on app/views/hyrax/homepage/_home_content.html.erb
> +        <% if @member_works.length == 0 %>
Cool yeah ill test it out. Im not even sure how often we'll run into any featured collections with one work or two works in it so the default will run 99% of the time, but to get to wireframe consistent we needed to add the placeholders.

2022-12-07 20:25 UTC, CGillen approved these changes

2022-12-07 22:54 UTC, merged