Add in new content to the how-to page
OregonDigital/OD2 pull request #2893
Opened 2023-07-20 21:53 UTC by lamtu1

`In Progress:` Add in content on the `how-to` page with new content and layout.

2023-07-20 21:54 UTC, lamtu1 commented
`Fixed for Issue:`   #2101

2023-07-21 20:39 UTC, lamtu1 commented
`Quick Video:` Demoing the How-To Use page
https://github.com/OregonDigital/OD2/assets/111306182/1cbe603b-85ce-4812-8966-9b64433f4387

2023-07-27 19:48 UTC, straleyb commented
@lamtu1 Is this ready to go or still WIP?

2023-07-27 20:17 UTC, lamtu1 commented
@straleyb I think it is ready to go. We can have this up for now, and if anyone have anymore suggestion or edit, I can alter it later on.

2023-07-31 17:01 UTC, CGillen requested changes
What was your reasoning for styling this page different than the rest of the about pages?

2023-07-31 17:01 UTC, CGillen commented on app/views/oregon_digital/about/use.html.erb
> +<ol class="use_toc">
Good use of `ol`

2023-07-31 17:49 UTC, lamtu1 commented
> What was your reasoning for styling this page different than the rest of the about pages?

I did this styling different as I was following along the google docs requirement on the ticket. Here is the link to the [Google Doc](https://docs.google.com/document/d/17xaOFMCH-_5s-txlTIzroFF3369Q-chAm-EGau5Oay8/edit#heading=h.byqkkjiuntp6).

I was not sure what the stylization is for the about page, so I just layout based on this requirement as follow in the link above.

2023-07-31 20:11 UTC, CGillen commented
The layout looks great, but I don't see where they mentioned they needed different CSS-type styling.
You should also almost never use `display: table` It usually means you're either working with a hack, or have messed up your `<table>` somehow. Either way, it's really bad for a11y

2023-07-31 20:35 UTC, lamtu1 commented
@CGillen Ah I see, I was following a tutorial on how to use CSS to display the number like in the demo video on the table of content. And I created the CSS page to isolate the content only on that page out like some spacing issue between `<p>` and `<h3> or <h2>` tag and make it only affecting on that `how-to` page. But I can rework it on the `display: table`and if we are sticking with no CSS page, I can rework it as well to use our CSS only.

2023-07-31 20:40 UTC, CGillen commented
If you need a separate css file just for the how-to page, that's fine. Just try to be aware of the font/text styling, to keep it consistent with the rest of the site. There should be some helper classes for some common resizing/styling fonts here
https://github.com/OregonDigital/OD2/blob/master/app/assets/stylesheets/oregon_digital/fonts.scss

stuff like `.lato-p`, or `.mw-lg`. Those aren't ones I specifically want you to use somewhere, they're just examples of the kinds of classes that we commonly use to keep fonts consistent

2023-07-31 20:50 UTC, lamtu1 commented
I will do that. I will fix that `display: table` in the css and beware of the other pages, and look how to apple consistency based on the `fonts.scss` file. Thank you for the feedback @CGillen

2023-08-02 21:05 UTC, CGillen commented
Can you post another screenshot? I'm worried some text is still serif and that just doesn't feel right. All font should be `lato`

2023-08-02 21:42 UTC, lamtu1 commented
Here some screenshot

<img width="1496" alt="Screenshot 2023-08-02 at 2 39 30 PM" src="https://github.com/OregonDigital/OD2/assets/111306182/60a1abf1-2183-40e7-99d4-76c0f9dab24f">

<img width="1496" alt="Screenshot 2023-08-02 at 2 39 45 PM" src="https://github.com/OregonDigital/OD2/assets/111306182/9a997ace-7c36-46ca-936d-829dcbbc89c8">

2023-08-04 18:01 UTC, CGillen approved these changes

2023-08-04 19:32 UTC, merged