First pass for tombstones
OregonDigital/OD2 pull request #2987
Opened 2023-11-21 19:18 UTC by straleyb

Not ready yet. Still needs more testing.

Fixes #1021

2023-11-28 20:49 UTC, straleyb commented
@CGillen This'll be ready once tests pass but its working as expected so its good for some review.

2023-11-29 20:49 UTC, CGillen requested changes

2023-11-29 20:49 UTC, CGillen commented on app/views/hyrax/base/_show_actions.html.erb
> +    <% if @presenter.workflow.actions.present? && @presenter.solr_document['workflow_state_name_ssim'] && @presenter.solr_document['workflow_state_name_ssim'].first.capitalize == 'Deposited' %>
You should be able to shorten this conditional with safe navigation: `&.`
`presenter.solr_document['workflow_state_name_ssim']&.first&.capitalize == 'Deposited'`
which will allow you to remove the `@presenter.solr_document['workflow_state_name_ssim']` presence check

2023-11-29 20:49 UTC, CGillen commented on app/views/hyrax/base/_show_actions.html.erb
> +    <% if @presenter.workflow.actions.present? && @presenter.solr_document['workflow_state_name_ssim'] && @presenter.solr_document['workflow_state_name_ssim'].first.capitalize == 'Deposited' %>
or remove the `#capitalize` and compare like you do in `app/views/hyrax/base/show.html.erb`

2023-11-29 21:15 UTC, CGillen approved these changes

2023-11-29 21:15 UTC, merged